name: http_cache
description: A starting point for Dart libraries or applications.
version: 0.1.6
repository: https://github.com/pti/http_cache/

environment:
  sdk: ^3.8.1

dependencies:
  http: ^1.4.0
  path: ^1.9.1
  crypto: ^3.0.6
  collection: ^1.19.1
  rxdart: ^0.28.0
  http_parser: ^4.1.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
